apiVersion: v2
name: generic
description: A generic Helm chart for Kubernetes

type: application
version: 0.2.1
appVersion: latest
maintainers:
  - name: colearendt
    email: helm@arendt.life
    url: https://github.com/colearendt
