apiVersion: v2
name: generic
description: A generic Helm chart for Kubernetes

type: application
version: 0.2.6
appVersion: latest
maintainers:
  - name: colearendt
    email: helm@colearendt.com
    url: https://github.com/colearendt
