name: traefik-forward-auth
description: Deploy traefik-forward-auth
version: 0.0.15
apiVersion: v1
sources:
  - https://github.com/thomseddon/traefik-forward-auth
maintainers:
  - name: colearendt
    email: helm@colearendt.com
    url: https://github.com/colearendt
