name: traefik-forward-auth
description: Deploy traefik-forward-auth
version: 0.0.3
apiVersion: v1
sources:
  - https://github.com/thomseddon/traefik-forward-auth
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/sol-eng
