apiVersion: v2
name: postgrest
description: A Helm chart for deploying Postgrest to Kubernetes
type: application
version: 0.3.0
appVersion: v8.0.0
icon: https://avatars.githubusercontent.com/u/15115011?s=200&v=4
maintainers:
  - name: colearendt
    email: helm@colearendt.com
    url: https://github.com/colearendt
