{{- if .Values.dockerConfigJson.username }}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ include "ghcr.fullname" . }}
data:
  .dockerconfigjson: {{- include "ghcr.authSecret" ( dict "username" .Values.dockerConfigJson.username "password" .Values.dockerConfigJson.password ) | nindent 4 }}
{{- end }}
